### ISSUE TITLE
MISC

### ISSUE THREAD

**Issue by bee0060** [liangshuai/vue#2]
内部培训的ppt？

模板字符串的示例代码有点小问题，少了` 符号

```
let str = `Hello ${name}`
```

**Comment by liangshuai** [comment]
@bee0060 
是的， 主要是因为跟Markdown语法中的｀ 相互冲突了， 当时没注意，后来发现没有转义

**Comment by bee0060** [comment]
哈哈··  在github里没事，你看我的代码里直接写了
